# Generated by Django 2.2.7 on 2019-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datefrom',
            field=models.DateField(default='2019-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='dateto',
            field=models.DateField(default='2019-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
