# Generated by Django 2.2.7 on 2019-11-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191111_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='datefrom',
            new_name='dateFrom',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='dateto',
            new_name='dateTo',
        ),
    ]
