# Generated by Django 2.2.7 on 2019-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191113_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateTo',
            field=models.DateTimeField(),
        ),
    ]
