# Generated by Django 2.2.7 on 2019-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191114_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
            ],
        ),
    ]
