# Generated by Django 2.2.7 on 2019-11-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191114_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
