# Generated by Django 2.2.7 on 2019-11-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetCategories',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_col', models.CharField(max_length=300)),
                ('iddataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DataSet')),
            ],
        ),
    ]
