# Generated by Django 2.2.7 on 2019-11-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_datasetcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetColumns',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_col_cont', models.CharField(blank=True, max_length=300, null=True)),
                ('x_col_categ', models.CharField(blank=True, max_length=300, null=True)),
                ('x_col_id', models.CharField(blank=True, max_length=300, null=True)),
                ('y_col', models.CharField(max_length=300)),
                ('iddataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.DataSet')),
            ],
        ),
        migrations.DeleteModel(
            name='DataSetCategories',
        ),
    ]
