# Generated by Django 2.2.7 on 2019-11-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20191118_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSetColumns',
        ),
    ]
