# Generated by Django 2.2.7 on 2019-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_dataset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
